name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout the code
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag playwright-test-local:latest
    - name: Docker Run Action
      run: docker container run -it -v ${{ github.workspace }}/report:/tmp/report playwright-test-local:latest
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: ${{ github.workspace }}/report
